language: node_js
node_js:
  - "9.4"
  - "9.3"
  - "9.2.1"
  - "9.2"
  - "9.1"
  - "9.0"
  - "8.9.4"
  - "8.8"
  - "8.7"
  - "8.6"
  - "8.5"
  - "8.4"
  - "8.3"
  - "8.2"
  - "8.1"
  - "8.0"
  - "7"
  - "6"
  - "5"
  - "4"
after_script: "npm run-script coveralls"
